format = """
$directory\
$git_branch\
$git_status\
$c\
$elixir\
$golang\
$java\
$nodejs\
$python\
$rust\
$docker_context\
$fill\
$ruby\
$cmd_duration $time\
$line_break\
$character"""

[fill]
symbol = " "

[cmd_duration]
min_time = 2_000
style = "italic dark_gray"
format = "levou [$duration]($style) "

[jobs]
symbol = "ï€“"
style = "bold red"
number_threshold = 4
symbol_threshold = 0

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ](bold red)"
vicmd_symbol = "[â®](bold blue)" # Para quem usa modo VI

# --- ConfiguraÃ§Ã£o dos MÃ³dulos ---
[directory]
style = "blue"
truncation_length = 2
truncate_to_repo = false

[git_branch]
symbol = "ï˜ "
style = "bold green"

[git_status]
style = "red"
conflicted = "ğŸ³"
ahead = "â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
up_to_date = "âœ“"
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "Â»"
deleted = "âœ˜"

# Linguagens e Ferramentas (Usando cores da paleta para consistÃªncia)

[c]
symbol = "î˜ "
style = "bold yellow"

[docker_context]
symbol = "ïŒˆ "
style = "bold blue"

[elixir]
symbol = "î‰µ "
style = "bold purple"

[golang]
symbol = "î˜§ "
style = "bold cyan"

[java]
symbol = "î‰– "
style = "bold red"

[nodejs]
symbol = "îœ˜ "
style = "bold green"

[python]
symbol = "î˜† "
style = "bold yellow"

[ruby]
symbol = "îˆ¾ "
style = "bold red"
format = "[$symbol($version )]($style)"

[rust]
symbol = "ï€“ "
style = "bold dark_gray"

